### ISSUE TITLE
Event not working with default and custom events

### ISSUE THREAD

**Issue by arditokshtuni** [dillingham/nova-button#9]
My code for custom event
------------------------------
EventServiceProvider.php
------------------------------
'App\Events\ActivateUser' => [
            'App\Listeners\ActivateUserListener',
        ],
        'App\Events\DeactivateUser' => [
            'App\Listeners\DeactivateUserListener',
        ],
        '\NovaButton\Events\ButtonClick' => [
            'App\Listeners\NovaButtonListener',
        ],

---------------------------
App\Nova\User.php
--------------------------

Button::make('Activate')
                ->event('App\Events\ActivateUser')
                ->visible($this->status == 0)
                ->confirm('Are you sure?')
                ->style('success-outline'),
            
Button::make('Deactivate')
                ->event('App\Events\DeactivateUser')
                ->visible($this->status == 1)
                ->confirm('Are you sure?')
                ->style('danger-outline'),

----------------------------------
App\Events\ActivateUser.php
----------------------------------
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class ActivateUser
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('channel-name');
    }
}

----------------------------------
App\Events\DeactivateUser.php
----------------------------------
<?php

namespace App\Events;

use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

class DeactivateUser
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('channel-name');
    }
}

-----------------------------------------------
App\Listeneres\ActivateUserListener.php
-----------------------------------------------
<?php

namespace App\Listeners;

use App\Events\ActivateUser;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class ActivateUserListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  ActivateUser  $event
     * @return void
     */
    public function handle(ActivateUser $event)
    {
        $event->resource->status = 1;
        $event->resource->save();
    }
}

-----------------------------------------------
App\Listeneres\ActivateUserListener.php
-----------------------------------------------
<?php

namespace App\Listeners;

use App\Events\DeactivateUser;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class DeactivateUserListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  DeactivateUser  $event
     * @return void
     */
    public function handle(DeactivateUser $event)
    {
        $event->resource->status = 0;
        $event->resource->save();
    }
}

-----------------------------------------------
App\Listeneres\NovaButtonListener.php
-----------------------------------------------
<?php

namespace App\Listeners;

class NovaButtonListener
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  ActivateUser  $event
     * @return void
     */
    public function handle($event)
    {
        Log::info('Ardit'.$event);
        if ($event->key == 'activate-user') {
            $event->resource->status = 1;
            $event->resource->save();
        }

        if ($event->key == 'deactivate-user') {
            $event->resource->status = 0;
            $event->resource->save();
        }
        
    }
}

#I have tried with both my custom events and default events
But i get always failed, i also cleared config, cache, view, run key generate,
in log file i see something like this: 

[2019-01-25 20:49:39] production.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php:44)
[stacktrace]
#0 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\helpers.php(1027): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(NULL)
#1 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php(48): tap(NULL, Object(Closure))
#2 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Encryption\\EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)
#3 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(776): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(658): Illuminate\\Container\\Container->build(Object(Closure))
#5 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(609): Illuminate\\Container\\Container->resolve('encrypter', Array)
#6 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(735): Illuminate\\Container\\Container->make('encrypter', Array)
#7 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(912): Illuminate\\Foundation\\Application->make('encrypter')
#8 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(840): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#9 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(807): Illuminate\\Container\\Container->resolveDependencies(Array)
#10 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(658): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#11 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(609): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#12 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(735): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#13 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(215): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#14 C:\\xampp\\htdocs\\parkingbadge\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(189): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#15 C:\\xampp\\htdocs\\parkingbadge\\public\\index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#16 {main}
"} 

Please help me solve this issue, thanks

**Comment by arditokshtuni** [comment]
The app works fine but the Action always return Failed

**Comment by dillingham** [comment]
@arditokshtuni no its not. You need to accept the $resource,$key

```php

class ActivateUser
{
use Dispatchable, InteractsWithSockets, SerializesModels;

public $resource;
public $key;

public function __construct($resource, $key)
{
    $this->resource = $resource;
    $this->key = $key;
}
```

**Comment by arditokshtuni** [comment]
@dillingham i just tried and it is not working :(
even with default Event and with this Field in my User Resource
`Button::make('Deactivate', 'deactivate-user')->visible($this->status == 1)->confirm('Are you sure?')->style('danger-outline'),
Thanks for your response :)
`

**Comment by dillingham** [comment]
@arditokshtuni triple check your code 👍

**Comment by arditokshtuni** [comment]
So the error is in package? @dillingham

**Comment by dillingham** [comment]
triple check **your code**, this is not a bug in the package. take care

**Comment by arditokshtuni** [comment]
ok thanks, if you will provide a full example of field/event/listener in documentation it will be better not only for me but all others, thanks, great work

**Comment by arditokshtuni** [comment]
@dillingham the error was that i was running my app with apache virtualhost like: website.test and when i served with php artisan serve, it works fine. So maybe there is a bug in package for the root url, for example we should define a .env variable for this package which will be used in your package. I am just suggesting that the requests should go in relative path and not absolute path.

**Comment by arditokshtuni** [comment]
yes i saw that code but why is not working with virtual host? in my network i do not even see the origin header attribute that is in request when laravel app uses artisan:serve
My .env
APP_URL=http://localhost

I tried:
APP_URL=http://localhost/myapp/public
APP_URL=http://myapp.test

And it is not working with these three with virtual host

Thanks for reply, @dillingham

**Comment by dillingham** [comment]
Again, this has nothing to do with this package.
Please ask on discord or something
https://discord.gg/ftpgm2
